import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Header } from '@/components/Header';
import './globals.css';
import StoreProvider from './StoreProvider';
import HeaderEO from '@/components/EO/HeaderEO';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <HeaderEO></HeaderEO>
          <Header />
          <div className="min-w-[360px] md:max-w-[1920px] m-auto">
            {children}
          </div>
        </body>
      </html>
    </StoreProvider>
  );
}
