'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Header } from '@/components/Header';
import './globals.css';
import StoreProvider from './StoreProvider';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const queryClient = new QueryClient();
  return (
    <QueryClientProvider client={queryClient}>
      <StoreProvider>
        <html lang="en">
          <head>
            <script
              type="text/javascript"
              src="https://app.sandbox.midtrans.com/snap/snap.js"
              data-client-key="<CLIENT-KEY>"
            ></script>
          </head>
          <body className={inter.className}>
            <Header />
            <div className="min-w-[360px] md:max-w-[1920px] m-auto">
              {children}
            </div>
          </body>
        </html>
      </StoreProvider>
    </QueryClientProvider>
  );
}
